### ISSUE TITLE
Image of the signatures

### ISSUE THREAD

**Issue by danizuu** [HebaNAS/IBM-Watson-Studio-Enablement#1]
Hello,
I would like to try the Visual Recognition model notebook. Unfortunately I cannot access your box and download images. 
Can you provide me access to box or send me the signature image files?

**Comment by HebaNAS** [comment]
Hi @danizuu,

Here’s the tutorial for signature fraud with alternative links, you can follow that. It’s using Watson Studio’s deep learning tools, not Visual Recognition, but it’s using the same dataset.

https://developer.ibm.com/tutorials/create-and-experiment-with-dl-models-using-nn-modeler/

The links on box here are not working as the account has been deleted.

**Comment by Danizu** [comment]
Hi Heba, the zip file I build with the original dataset is too big to be uploaded. I'm a colleague but I'm not able to find you in our internal address book
I'm zuppini Italy
